apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002  # Manually specify the NodePort, or let Kubernetes assign it
  selector:
    app: backend
