apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: NodePort
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30001  # Manually specify the NodePort, or let Kubernetes assign it
  selector:
    app: angular-app

